server:
  port: 8084  # Change this port for different services (e.g., 8082 for order-service)

spring:
  application:
    name: order-microservice-webclient-duilder # Change this name for different services (e.g., order-service)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/